### ISSUE TITLE
Help with gettin it setup

### ISSUE THREAD

**Issue by No12** [Kr4ken-9/TatsumakiFarmer#86]
could someone walk me though how to get DAB running as i cant rap my head around it.

**Comment by anas-p13** [comment]
it's all explained in readme.md 
is there any specific problem you are facing?

**Comment by No12** [comment]
> it's all explained in readme.md
> is there any specific problem you are facing?

i need help with the pip instal
![Capture](https://user-images.githubusercontent.com/61977742/92129525-8c9e9a00-edfb-11ea-8d6a-a3350d246c37.PNG)

**Comment by anas-p13** [comment]
oh i see, i will try my best, not really a programmer here
so first u gotta install python and git for desktop (https://git-scm.com/downloads)
then in the dab directory open git bash
![image](https://user-images.githubusercontent.com/67867904/92130764-8d94f300-ee1e-11ea-8239-49e6e0a4627c.png)
and then enter this command ``python -m pip install -r requirements.txt``
thats it this will install all the pips

but if u wanna do with cmd
then u gotta do one at a time
like ``pip install discord.py`` and so on

**Comment by No12** [comment]
> oh i see, i will try my best, not really a programmer here
> so first u gotta install python and git for desktop (https://git-scm.com/downloads)
> then in the dab directory open git bash
> ![image](https://user-images.githubusercontent.com/67867904/92130764-8d94f300-ee1e-11ea-8239-49e6e0a4627c.png)
> and then enter this command `python -m pip install -r requirements.txt`
> thats it this will install all the pips
> 
> but if u wanna do with cmd
> then u gotta do one at a time
> like `pip install discord.py` and so on

ah i see that helps alot thank you ^^

**Comment by No12** [comment]
well ive gotten this far but im unsure what to put for id??

> oh i see, i will try my best, not really a programmer here
> so first u gotta install python and git for desktop (https://git-scm.com/downloads)
> then in the dab directory open git bash
> ![image](https://user-images.githubusercontent.com/67867904/92130764-8d94f300-ee1e-11ea-8239-49e6e0a4627c.png)
> and then enter this command `python -m pip install -r requirements.txt`
> thats it this will install all the pips
> 
> but if u wanna do with cmd
> then u gotta do one at a time
> like `pip install discord.py` and so on

![Capture](https://user-images.githubusercontent.com/61977742/92138464-4bf84e00-ee06-11ea-9d96-025e49e115a1.PNG)

**Comment by anas-p13** [comment]
https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-

**Comment by No12** [comment]
> https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-

thanks also what do i do with this, or how to i add the hash to the db???
![Capture](https://user-images.githubusercontent.com/61977742/92145410-1d7f7080-ee10-11ea-811e-84e693d52ae5.PNG)

**Comment by anas-p13** [comment]
> > https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-
> 
> thanks also what do i do with this, or how to i add the hash to the db???
> ![Capture](https://user-images.githubusercontent.com/61977742/92145410-1d7f7080-ee10-11ea-811e-84e693d52ae5.PNG)

#87
