### ISSUE TITLE
Missing Hash for Farfetch'd

### ISSUE THREAD

**Issue by No12** [Kr4ken-9/TatsumakiFarmer#87]
d6a594b7d5b7d537cf27cd258c30dd223b1c5a4ec923265b0af9173b0f3ec364
Hash for Farfetch'd also im using poketwo.
![Capture](https://user-images.githubusercontent.com/61977742/92145937-de055400-ee10-11ea-97cd-e62604ebf67d.PNG)
is there a way to manually add it?

**Comment by anas-p13** [comment]
> is there a way to manually add it?

yes u can edit it in pokebois.json
![image](https://user-images.githubusercontent.com/67867904/92146368-08680900-ee33-11ea-983b-08a8aa4f5bcc.png)
just replace that with 
"d6a594b7d5b7d537cf27cd258c30dd223b1c5a4ec923265b0af9173b0f3ec364": "Farfetch'd",

**Comment by No12** [comment]
thanks for the help
