### ISSUE TITLE
Missing Pokemon

### ISSUE THREAD

**Issue by devraza** [Kr4ken-9/TatsumakiFarmer#98]
Kirlia isn't able to be caught - It's not in the database

**Comment by devraza** [comment]
Golem isn't able to be caught - It's not in the database

**Comment by devraza** [comment]
Machamp isn't able to be caught - It's not in the database

**Comment by devraza** [comment]
Pikipek isn't able to be caught - It's not in the database

**Comment by dolfies** [comment]
Same with nidoran
